language: php

php:
  - 7.2.5
  - 7.3
  - 7.4

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 7.2.5
      env: setup=stable

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi

script: vendor/bin/phpunit
